test
t-komiya2222/Task_Test pull request #1
Opened 2022-02-10 08:29 UTC by t-komiya2222

2022-02-15 09:06 UTC, tatsukoni requested changes
返しました！

2022-02-15 09:06 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +        $path = $request->file('image')->store('public');
画像アップロードなんですが、Laravelのfilesystems機能を使って、ローカルディスクにアップロードするようにしてみましょうか。
（ファイルシステムは業務で用いるため、それを体験して頂くためです）

使い方・実装方法は以下を参考にして頂けると:pray:
https://readouble.com/laravel/6.x/ja/filesystem.html

2022-02-15 09:06 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +        Post::where('id', $id)->delete();
データ変更（登録・更新・削除）を伴う場合については、try catch文を使って、エラーハンドリングを実施するようにしてみましょうか！

[参考](https://qiita.com/Chelsea/items/59436cfda149a6ac6c91)

2022-02-15 09:39 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +        Post::where('id', $id)->delete();
[エラーハンドリングの参考](https://readouble.com/laravel/6.x/ja/errors.html)

2022-02-15 09:39 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +        Post::where('id', $id)->delete();
[Laravelでのログ出力方法](https://readouble.com/laravel/6.x/ja/logging.html)

2022-02-15 09:40 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +        Post::where('id', $id)->delete();
「エラーをcatchして、ログに出力する」
という部分まで実装して頂けると:pray:

2022-02-16 04:13 UTC, t-komiya2222 commented on app/Http/Controllers/PostController.php
> +        $path = $request->file('image')->store('public');
[6580d8e](https://github.com/t-komiya2222/Task_Test/pull/1/commits/6580d8ee4cc619ee8b41b8ba47edf9ae14ebfea4)
filesystem利用して修正してみました。

2022-02-17 08:49 UTC, t-komiya2222 commented on app/Http/Controllers/PostController.php
> +        Post::where('id', $id)->delete();
・try-catchの追加 [be59a0d](https://github.com/t-komiya2222/Task_Test/pull/1/commits/be59a0d3a7546c178974b826a56d060d39c33dd6)

・try-catch ログ出力追加[c311ad3](https://github.com/t-komiya2222/Task_Test/pull/1/commits/c311ad317085f315f2f6f17b468fbb736a4a8b12)

2022-02-17 11:42 UTC, tatsukoni requested changes
返しました！

2022-02-17 11:42 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +use \Exception;
`use Exception;`
で良いはずです！

2022-02-17 11:42 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +                ]);
```
Post::create([
    'user_id' => $request->user_id,
    'title' => $request->title,
    'description' => $request->description,
    //第一引数は追加したいパス 第二引数は保存したい場所?　第三引数は指定したいファイル名
     'image' => Storage::putFileAs('', $request->file('image'), $file_name)
]);

```

のような感じで、改行を入れてみましょうか！
この辺は、vscodeだと自動整形・赤線出してくれるツールもあるので、参考にしてみてください。
- [php cs fixer](https://marketplace.visualstudio.com/items?itemName=junstyle.php-cs-fixer)
- [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client)

2022-02-17 11:42 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +                ]);
ちなみにOurPhotoでは、[PSR-2](http://www.infiniteloop.co.jp/docs/psr/psr-2-coding-style-guide.html)というコーディング規約に準拠していたりしています。

この辺は、この通りでなくても動きはするのですが、実際に業務に入られる際は守って頂きたいので、ぜひ今のうちからキャッチアップ頂けると良いかと思います:pray:

2022-02-17 11:42 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +            echo $ex->getMessage();
ログに出していれば、`echo`はしなくて良いと思います！
（`echo`は、実際のコードではあまり使わないと思います）

2022-02-17 11:42 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +            \Log::error($ex->getMessage());
`use Illuminate\Support\Facades\Log;`

をしているので、`Log::error($ex->getMessage())`で良いはずです。

2022-02-17 11:42 UTC, tatsukoni commented on app/Http/Controllers/PostController.php
> +            if(isset($post_id)){
isset()は、true/falseの判定があやふやだったりするので、使う時には注意してみると良いかもしれません。。！
[参考](https://qiita.com/shinichi-takii/items/00aed26f96cf6bb3fe62)

2022-02-18 01:46 UTC, t-komiya2222 commented on app/Http/Controllers/PostController.php
> +use \Exception;
[7d06f7c](https://github.com/t-komiya2222/Task_Test/pull/1/commits/7d06f7c56ba7ced2aeaa2fededcb151f60613846)
/削除して修正しました！

2022-02-18 02:10 UTC, t-komiya2222 commented on app/Http/Controllers/PostController.php
> +                ]);
[f788baa](https://github.com/t-komiya2222/Task_Test/pull/1/commits/f788baaefbf2e23ecba3df35ab194a31d42a5ec0)
改行追加しました！
また、記載いただいた拡張機能も導入しました。

2022-02-18 02:39 UTC, t-komiya2222 commented on app/Http/Controllers/PostController.php
> +            \Log::error($ex->getMessage());
[f478695](https://github.com/t-komiya2222/Task_Test/pull/1/commits/f4786954bae11cbb3448b57ac35410b3911a6671)
\を削除して修正しました！

2022-02-18 04:07 UTC, t-komiya2222 commented on app/Http/Controllers/PostController.php
> +            echo $ex->getMessage();
[eccfce9](https://github.com/t-komiya2222/Task_Test/pull/1/commits/eccfce9243df96f8e8a3f23329005b96d6d70315)
echo削除しました！
それに合わせて画面側のメッセージ表示方法を変更しました。

2022-02-18 04:40 UTC, tatsukoni approved these changes
良いと思います！

2022-02-18 06:00 UTC, merged